(() => {
  "use strict";
  const $ = (s, root = document) => root.querySelector(s);
  const $$ = (s, root = document) => [...root.querySelectorAll(s)];
  const escapeHtml = value => String(value ?? "").replace(/[&<>"']/g, c => ({"&":"&amp;","<":"&lt;",">":"&gt;","\"":"&quot;","'":"&#39;"}[c]));
  const crops = {
    archiveHero:["archive-reference.png",249,153,806,350], archivePattern:["archive-reference.png",264,615,422,139], archiveTool:["archive-reference.png",732,615,417,139], archiveMaker:["archive-reference.png",1196,615,421,139],
    cultureMain:["culture-reference.png",264,196,402,428], culture1:["culture-reference.png",268,769,151,125], culture2:["culture-reference.png",433,769,154,125], culture3:["culture-reference.png",602,769,150,125], culture4:["culture-reference.png",765,769,149,125], culture5:["culture-reference.png",928,769,153,125], culture6:["culture-reference.png",1097,769,150,125],
    modelBefore:["tryon-reference.png",1165,194,218,191], modelAfter:["tryon-reference.png",651,194,472,697], sceneTryon:["tryon-reference.png",1166,499,471,319],
    hall:["exhibit-reference.png",190,159,1025,601], weave:["weave-reference.png",239,150,898,592]
  };
  const crop=(name,extra="")=>{const [file,x,y,w,h]=crops[name];return `<div class="crop ${extra}" style="--ratio:${w}/${h}"><img src="./assets/${file}" alt="" draggable="false" loading="lazy" style="width:${(1672/w*100).toFixed(4)}%;left:0;top:0;transform:translate(${(-x/1672*100).toFixed(4)}%,${(-y/941*100).toFixed(4)}%)"></div>`;};
  const routes=[
    ["archive","锦带档案","▣"],["culture","文化解码","◇"],["create","共创工坊","✎"],["tryon","AI试戴","♙"],["weave","经纬工坊","▦"],["exhibit","数字展厅","⌂"]
  ];
  let motifs=Array.from({length:35},(_,i)=>`纹样 ${String(i+1).padStart(2,"0")}`);
  let motifKinds=motifs.map((_,i)=>{const n=i+1;return n===1||n===3||n===16||n===19||n>=22?"混合":n>=12&&n<=15||n>=17&&n<=18||n>=20&&n<=21?"红白":"蓝白";});
  const motifImage=id=>`./assets/motifs/${String(id+1).padStart(2,"0")}.jpg`;
  const motifVisual=(id,extra="")=>`<img class="motif-photo ${extra}" src="${motifImage(id)}" alt="${escapeHtml(motifs[id])} · ${escapeHtml(motifKinds[id])}配色的锦带局部" loading="lazy" draggable="false">`;
  const palettes=[{name:"朱砂红",hex:"#a33f38"},{name:"暖金",hex:"#d4a052"},{name:"藏蓝",hex:"#244c6d"},{name:"青绿",hex:"#3e7b78"},{name:"米白",hex:"#e7d9bf"},{name:"藕紫",hex:"#a795b7"},{name:"桃粉",hex:"#d97981"},{name:"墨黑",hex:"#26282b"}];
  const presets=[{name:"蓝白组合",ids:[3,4,5,6,9,6,5,4,3]},{name:"红白组合",ids:[11,12,13,14,17,14,13,12,11]},{name:"多彩组合",ids:[0,2,15,18,21,22,23,24,25]}];
  const cultureTabs={meaning:"这是一则用于展示交互的纹样解读示例。正式版将依据舟曲实地采集资料，把图形结构、当地称谓、使用场景及寓意逐项关联，并标注具体出处。",source:"当前图片来自团队提供的原型图，尚未对应到可核实的实物编号或口述记录。正式档案应补充采集时间、地点、授权情况和传承人审核意见。",usage:"可将选中的视觉元素带入共创工坊，组合成个人数字作品。系统推荐只代表设计启发，不等于传统寓意或真实可织造性已经验证。"};
  let steps=[
    {title:"摆放工具",desc:"文献先铺设木制支撑、挑线用“用叉”和压线用“打玛”等工具；在画面中辨认各自的位置。",action:"进入拉线"},
    {title:"拉线（布线）",desc:"按照预定图案往返排列彩线，形成线组；线组数量与锦带宽度有关，此处仅演示变化趋势。",action:"完成拉线示意"},
    {title:"安置提经杆（“尼”）",desc:"布线后经线分为上下两层；依次安置三组提经杆，便于分组提起经线。",action:"完成三组提经"},
    {title:"安置固定杆（“丝”）",desc:"将尚未织到的线组绕在竹制固定杆上，整理并固定线束。",action:"确认固定杆"},
    {title:"“搭”（织造）",desc:"坐姿伸脚保持张力，腰部固定近端；用“用叉”按图案挑线、引纬，再用“打玛”压紧，反复织造。",action:"查看成带回顾"},
    {title:"成带回顾 · 数字演示",desc:"回顾前五段文献工序。文献没有单列取带与收边的完整动作，页面不把它们演成已核实步骤。",action:"完成体验"}
  ];
  let chapters=[
    {name:"序厅 · 锦带之美",image:"gallery-photo",desc:"从代表锦带进入展览，认识不同用途和视觉风格。"},
    {name:"代表锦带",image:"archive-photo",desc:"近距离观察纹样、配色与织物细节。"},
    {name:"织造工具",image:"gallery-tools",desc:"观察手工织造所使用的工具及其功能。"},
    {name:"传承故事",image:"gallery-story",desc:"通过口述与影像了解织带人的经历。"},
    {name:"当代新生",image:"model-photo",desc:"看看传统纹样如何进入当代生活。"},
    {name:"沉浸影像",image:"weave-photo",desc:"以第一视角理解锦带制作过程。"}
  ];
  const defaults={route:"archive",archiveFilter:"全部",archiveQuery:"",archiveItem:0,cultureTab:"meaning",suggestion:0,theme:"万事顺遂",preset:0,cells:[...presets[0].ids],selectedMotif:0,motifFilter:"全部",palette:0,placement:"head",photoUrl:null,scale:100,x:50,y:50,tryonShow:true,tryonDesign:"custom",weaveStep:0,weaveCount:12,weaveColor:0,weaveSelected:[],weaveRounds:0,weavePass:false,weaveBeat:false,weaveTools:false,weaveLayout:false,weaveHeddles:0,weaveFixed:false,chapter:0};
  let state={...defaults};let toastTimer;let speech=null;let serverArchives=null;let backendOnline=false;let savedDesigns=[];let activeDesignId=null;let progressTimer=null;
  async function api(path,options={}){const res=await fetch(`/api${path}`,{credentials:"same-origin",headers:{"Content-Type":"application/json"},...options});const data=await res.json();if(!res.ok)throw new Error(data.error||`请求失败：${res.status}`);return data;}
  async function connectBackend(){try{const data=await api("/bootstrap");if(!Array.isArray(data.motifs)||!Array.isArray(data.archives))return;backendOnline=true;motifs=data.motifs.map(m=>m.title);motifKinds=data.motifs.map(m=>m.kind);serverArchives=data.archives.map(a=>({kind:a.kind,title:a.title,image:a.image,summary:a.summary,tags:a.tags,id:a.id,isDemo:a.isDemo,source:a.source,rightsStatus:a.rightsStatus,verificationStatus:a.verificationStatus,era:a.era,material:a.material,dimensions:a.dimensions}));chapters=data.chapters.map(c=>({name:c.name,image:c.image,desc:c.desc}));steps=data.steps.map(s=>({title:s.title,desc:s.desc,action:s.action}));render();savedDesigns=await api("/designs");const progress=await api("/weave-progress");if(progress){state.weaveStep=progress.step;state.weaveCount=progress.count;state.weaveColor=progress.color;state.weaveRounds=progress.rounds;state.weaveSelected=progress.selected;state.weaveHeddles=progress.heddles;state.weaveTools=progress.tools;state.weaveLayout=progress.layout;state.weaveFixed=progress.fixed;state.weavePass=progress.pass;state.weaveBeat=progress.beat;}if(savedDesigns.length){loadDesign(savedDesigns[0],false);}if(state.route==="weave"||state.route==="create")render();}catch(e){console.warn("平台后端不可用，继续使用浏览器本地演示：",e.message);}}
  function loadDesign(work,notify=true){state.theme=String(work.title||defaults.theme).slice(0,20);state.cells=work.cells.map(n=>Number.isInteger(n)&&n>=0&&n<motifs.length?n:null);state.palette=Math.min(7,Math.max(0,Number(work.palette)||0));state.preset=-1;activeDesignId=work.id||null;if(state.route==="create")render();if(notify)toast(`已载入《${state.theme}》`);}
  function progressPayload(){return {step:state.weaveStep,count:state.weaveCount,color:state.weaveColor,rounds:state.weaveRounds,selected:state.weaveSelected,heddles:state.weaveHeddles,tools:state.weaveTools,layout:state.weaveLayout,fixed:state.weaveFixed,pass:state.weavePass,beat:state.weaveBeat};}
  function queueProgress(){if(!backendOnline)return;clearTimeout(progressTimer);progressTimer=setTimeout(()=>api("/weave-progress",{method:"PUT",body:JSON.stringify(progressPayload())}).catch(e=>console.warn("体验进度保存失败：",e.message)),300);}
  function toast(message){const el=$("#toast");el.textContent=message;el.classList.add("show");clearTimeout(toastTimer);toastTimer=setTimeout(()=>el.classList.remove("show"),3200);}
  function modal(html){$("#modal-content").innerHTML=html;if(!$("#modal").open)$("#modal").showModal();}
  function sceneImage(name){if(name==="gallery-photo")return '<img class="photo-fill" src="./assets/virtual-gallery.png" alt="数字展厅概念场景">';if(name==="gallery-tools")return '<img class="photo-fill gallery-tools-photo" src="./assets/virtual-gallery.png" alt="数字展厅中的织造工具概念场景">';if(name==="gallery-story")return '<img class="photo-fill gallery-story-photo" src="./assets/virtual-gallery.png" alt="数字展厅中的传承故事概念场景">';if(name==="model-photo")return '<img class="photo-fill" src="./assets/system-model.png" alt="锦带当代佩戴概念摄影">';if(name==="weave-photo")return '<img class="photo-fill" src="./assets/weave-first-person.png" alt="第一视角织带概念场景">';if(name==="archive-photo")return '<img class="photo-fill" src="./assets/archive-brocade.png" alt="锦带概念摄影">';return crop(name);}
  function pageHead(title,subtitle,seal=""){return `<header class="page-head"><h1>${title}${seal?`<span class="seal">${seal}</span>`:""}</h1><p>${subtitle}</p></header>`;}
  function renderNav(){ $("#nav").innerHTML=routes.map(([id,label,icon])=>`<button class="nav-link ${state.route===id?"active":""}" data-route="${id}" ${state.route===id?'aria-current="page"':""}><span class="nav-icon" aria-hidden="true">${icon}</span><span>${label}</span></button>`).join("");}
  function route(id){if(!routes.some(item=>item[0]===id))id="archive";state.route=id;location.hash=id;render();window.scrollTo({top:0,behavior:"instant"});$("#sidebar").classList.remove("open");$("#menu-button").setAttribute("aria-expanded","false");}
  function render(){renderNav();const pages={archive:renderArchive,culture:renderCulture,create:renderCreate,tryon:renderTryon,weave:renderWeave,exhibit:renderExhibit};$("#main").innerHTML=pages[state.route]();}
  function renderKeepingMotifScroll(){const top=$("#motif-picker")?.scrollTop??0;render();const picker=$("#motif-picker");if(picker)picker.scrollTop=top;}
  function archiveItems(){if(serverArchives)return serverArchives;return [
    {kind:"实物",title:"几何菱花纹锦带",image:"archive-photo",summary:"多色纱线交织形成连续几何结构。图片仅作页面演示。",tags:"纹样 实物 菱形 几何"},
    {kind:"纹样",title:"莲花菱形纹",image:"archivePattern",summary:"重复与对称的图形结构，可用于观察纹样节奏。",tags:"纹样 菱形 花形"},
    {kind:"工艺",title:"手工织带工具",image:"archiveTool",summary:"呈现传统织带所用的木质工具与线组。",tags:"工艺 工具 木质"},
    {kind:"传承人",title:"织带人的故事",image:"archiveMaker",summary:"传承人影像与口述档案的展示位置。",tags:"传承人 口述 影像"},
    {kind:"纹样",title:"花形几何组合",image:"cultureMain",summary:"从实物局部放大，查看色彩与构图。",tags:"纹样 花形 色彩"},
    {kind:"工艺",title:"第一视角织造",image:"weave",summary:"观察腰脚固定、彩线排列及操作视角。",tags:"工艺 经线 织造"}
  ];}
  function renderArchive(){const items=archiveItems();const query=state.archiveQuery.trim().toLowerCase();const filtered=items.map((item,index)=>({...item,index})).filter(item=>(state.archiveFilter==="全部"||item.kind===state.archiveFilter)&&(!query||`${item.title}${item.summary}${item.tags}`.toLowerCase().includes(query)));const feature=items[state.archiveItem]||items[0];if(!feature)return `${pageHead("锦带数字档案","资料正在整理")}<p>暂无档案。</p>`;return `${pageHead("锦带数字档案","收录 · 记录 · 传承　让一根锦带的故事被看见","锦综")}
    <div class="archive-toolbar"><input id="archive-search" type="search" value="${escapeHtml(state.archiveQuery)}" placeholder="搜索纹样、工艺、传承人" aria-label="搜索档案"><button class="button ink" id="archive-search-button">搜索</button></div>
    <div class="chips" id="archive-filters" style="margin-bottom:16px">${["全部","纹样","实物","工艺","传承人"].map(kind=>`<button class="chip ${kind===state.archiveFilter?"active":""}" data-filter="${kind}">${kind}</button>`).join("")}</div>
    <div class="archive-feature panel">${sceneImage(feature.image)}<div class="archive-feature-copy"><span class="badge warn">${escapeHtml(feature.kind)} · ${feature.isDemo===false?"资料条目":"演示资料"}</span><h2>${escapeHtml(feature.title)}</h2><p>${escapeHtml(feature.summary)}</p><dl class="archive-meta"><dt>年代</dt><dd>${escapeHtml(feature.era||"待采集核验")}</dd><dt>材质</dt><dd>${escapeHtml(feature.material||"待补充")}</dd><dt>尺寸</dt><dd>${escapeHtml(feature.dimensions||"待测量")}</dd><dt>来源</dt><dd>${escapeHtml(feature.source||"原型概念素材；非正式馆藏记录")}</dd><dt>审核</dt><dd>${feature.verificationStatus==="verified"?"已标记核验":"待传承人及相关领域专家核验"}</dd></dl><button class="button secondary" data-detail="${state.archiveItem}">查看完整档案 →</button></div></div>
    <div class="content-divider"><h2>档案精选 <span class="muted small">${filtered.length} 条资料</span></h2><button data-filter="全部">查看全部 →</button></div>
    <div class="archive-grid">${filtered.map(item=>`<article class="archive-card panel"><button class="cropped-button" data-feature="${item.index}" aria-label="查看${escapeHtml(item.title)}">${sceneImage(item.image)}</button><div class="archive-card-body"><span class="badge">${escapeHtml(item.kind)}</span><h3>${escapeHtml(item.title)}</h3><p>${escapeHtml(item.summary)}</p><button data-detail="${item.index}">查看档案 →</button></div></article>`).join("")||'<p class="rule-note">没有匹配的资料，请更换关键词。</p>'}</div>`;}
  function renderCulture(){return `${pageHead("锦带文化解码","从一方纹样出发，连接纹样、色彩、寓意、场景、工艺与故事。","解码")}
    <div class="culture-layout"><figure class="culture-image" style="margin:0">${crop("cultureMain","rounded")}<figcaption><strong>选中纹样 · 视觉示例</strong><span class="muted small" style="float:right">放大观察图形结构</span></figcaption></figure>
    <section class="culture-map panel"><h2 class="section-title">文化要素关系图</h2><div class="map-center" aria-label="中心纹样">✥</div><div class="map-nodes">${[["纹样","图形构成"],["色彩","情感表达"],["寓意","文化解读"],["场景","使用情境"],["工艺","制作方法"],["故事","人的记忆"]].map(([a,b])=>`<button class="map-node" data-culture-node="${a}"><strong>${a}</strong><span>${b}</span></button>`).join("")}</div><p class="small muted">点击要素，查看它与纹样的关联说明。</p></section>
    <section class="culture-detail panel"><div class="segmented">${[["meaning","文化释义"],["source","来源依据"],["usage","推荐使用"]].map(([id,label])=>`<button class="tab ${state.cultureTab===id?"active":""}" data-culture-tab="${id}">${label}</button>`).join("")}</div><div class="culture-copy">${cultureTabs[state.cultureTab]}</div><h3 class="section-title">语音讲述</h3><div class="audio-box"><button id="speak-button" aria-label="朗读当前说明">▶</button><div class="audio-progress"></div><span class="small">浏览器语音演示</span></div><p class="small muted">使用浏览器语音朗读；正式口述音频需经授权采集。</p><div class="rule-note">待专家核验 · 本内容仅展示平台如何关联文化知识。</div></section></div>
    <div class="content-divider"><h2>相关纹样推荐</h2><button id="shuffle-suggestions">换一批 ↻</button></div><div class="culture-suggestions">${Array.from({length:6},(_,i)=>{const n=(i+state.suggestion)%6;return `<button class="suggestion ${n===state.suggestion?"active":""}" data-suggestion="${n}" aria-label="选择相关纹样 ${n+1}">${crop(`culture${n+1}`)}</button>`;}).join("")}<div class="suggestion-cta"><button class="button" data-route="create">用此纹样创作 →</button></div></div>`;}
  function createRibbon(){const order=Array.from({length:45},(_,i)=>i%9);return `<div class="ribbon-stack" style="border-color:${palettes[state.palette].hex}" role="img" aria-label="当前九宫格连续重复五次组成的长锦带预览">${order.map(index=>{const id=state.cells[index];return `<div class="motif-tile" data-source-cell="${index}">${id===null?"":`<img class="motif-photo" src="${motifImage(id)}" alt="" loading="lazy" draggable="false">`}</div>`;}).join("")}</div>`;}
  function renderCreate(){const filled=state.cells.filter(n=>n!==null).length;return `${pageHead("锦带共创工坊","以图案为语 · 织就属于你的锦带")}
    <div class="create-layout"><section class="panel create-panel"><h2 class="step-heading"><b>1</b>祝福主题</h2><div class="field"><label for="theme">为作品起个名字</label><input id="theme" maxlength="20" value="${escapeHtml(state.theme)}" placeholder="例如：万事顺遂"></div>
    <h2 class="step-heading"><b>2</b>选择模板</h2><div class="segmented" style="margin-bottom:9px"><button class="chip ${state.preset>=0?"active":""}" data-mode="preset">系统搭配</button><button class="chip ${state.preset<0?"active":""}" data-mode="free">自由设计</button></div><div class="preset-grid">${presets.map((p,i)=>`<button class="preset-card ${state.preset===i?"active":""}" data-preset="${i}" aria-label="选择${p.name}"><span class="preset-patterns">${p.ids.slice(0,3).map(id=>motifVisual(id)).join("")}</span><span>${p.name}</span></button>`).join("")}</div>
    <h2 class="step-heading" style="margin-top:15px"><b>3</b>纹样图片</h2><p class="small muted">来自团队旧仓库的 35 张锦带局部图；按原文件夹配色筛选，纹样名称与寓意待核对。</p><div class="chips">${["全部","蓝白","红白","混合"].map(s=>`<button class="chip ${state.motifFilter===s?"active":""}" data-motif-kind="${s}">${s}</button>`).join("")}</div><div class="selected-motif-preview">${motifVisual(state.selectedMotif)}<div><strong>${escapeHtml(motifs[state.selectedMotif])}</strong><span>${escapeHtml(motifKinds[state.selectedMotif])}配色 · 点击下方图片选择</span></div></div><div class="motif-picker" id="motif-picker">${motifs.map((m,i)=>state.motifFilter!=="全部"&&motifKinds[i]!==state.motifFilter?"":`<button class="${state.selectedMotif===i?"active":""}" data-motif="${i}" aria-label="选择${escapeHtml(m)}，${escapeHtml(motifKinds[i])}配色" aria-pressed="${state.selectedMotif===i}" title="${escapeHtml(m)} · ${escapeHtml(motifKinds[i])}">${motifVisual(i)}<span class="motif-id">${String(i+1).padStart(2,"0")}</span></button>`).join("")}</div>
    <h2 class="step-heading" style="margin-top:13px"><b>4</b>边框配色</h2><p class="small muted">原图颜色保持不变，仅调整数字作品的边框色。</p><div class="swatches">${palettes.map((p,i)=>`<button class="swatch ${state.palette===i?"active":""}" style="background:${p.hex}" data-palette="${i}" aria-label="${p.name}" title="${p.name}"></button>`).join("")}</div></section>
    <section class="panel create-panel"><h2 class="step-heading"><b>5</b>九宫格编辑</h2><p class="small muted">先选左侧纹样，再点击方格替换；也可拖动方格交换位置。</p><div class="grid-nine">${state.cells.map((id,i)=>`<button class="grid-cell" data-cell="${i}" draggable="true" aria-label="第 ${i+1} 格，${id===null?"空白":escapeHtml(motifs[id])}"><b>${i+1}</b>${id===null?"":motifVisual(id)}</button>`).join("")}</div><div class="grid-actions"><button class="button secondary" id="reset-grid">重置九宫格</button><button class="button secondary" id="random-grid">随机组合</button></div><p class="small muted">当前选中：${escapeHtml(motifs[state.selectedMotif])} · ${escapeHtml(motifKinds[state.selectedMotif])}配色 · 已填 ${filled}/9 格</p></section>
    <section class="panel create-panel preview-panel"><h2 class="step-heading"><b>6</b>效果预览</h2><div style="position:relative"><div class="preview-ribbon">${createRibbon()}<span class="ribbon-preview-note">九宫格单元 × 5 · 长锦带连续拼接示意</span></div><div class="preview-check"><strong>设计检查</strong><p>✓ ${filled}/9 格已编辑</p><p>✓ 可用于数字预览</p><p>○ 实际可织性待核验</p></div></div><div class="preview-actions"><button class="button" id="save-design">保存作品</button><button class="button secondary" data-route="tryon">去试戴 →</button></div><div class="grid-actions"><button class="button secondary" id="new-design">另存新作品</button><button class="button secondary" id="my-designs">我的作品${backendOnline?`（${savedDesigns.length}）`:""}</button></div><p class="small muted">${backendOnline?"作品保存在本机服务；同一浏览器可再次读取，不支持跨设备同步。":"后端未连接；当前仅保存至浏览器。"}</p></section></div>`;}
  function wearableStyle(){const x=50+(state.x-50)*.6,y=(state.placement==="head"?25:state.placement==="hair"?38:state.placement==="wrist"?75:60)+(state.y-50)*.38,w=(state.placement==="head"?43:state.placement==="hair"?35:state.placement==="wrist"?24:50)*state.scale/100;return `left:${x}%;top:${y}%;width:${w}%;background:${palettes[state.palette].hex}`;}
  function wearableCells(){const ids=state.tryonDesign==="custom"?state.cells:Array(9).fill(state.selectedMotif);return ids.map(id=>`<span style="background:${id===null?"#ead8be":"#fff"}" title="${id===null?"空格":motifs[id]}">${id===null?"":`<img src="${motifImage(id)}" alt="" loading="lazy">`}</span>`).join("");}
  function renderTryon(){return `${pageHead("锦上身 · AI试戴馆","以数字之艺，感受舟曲锦带的当代表达")}
    <div class="tryon-layout"><section class="panel tryon-column"><h2 class="section-title">1. 照片来源</h2><div class="source-choices"><label class="button file-label">上传照片<input id="photo-upload" type="file" accept="image/png,image/jpeg,image/webp"></label><button class="button secondary" id="system-photo">系统模特</button></div><p class="small muted">照片只在本机浏览器预览，不上传服务器。</p>
    <h2 class="section-title">2. 选择锦带图案</h2><div class="tryon-motifs">${[0,3,11,15,18,21,27,32].map(i=>`<button class="${state.tryonDesign==="system"&&state.selectedMotif===i?"active":""}" data-motif="${i}" aria-label="选择${motifs[i]}" title="${motifs[i]}">${motifVisual(i)}</button>`).join("")}</div><button class="button ${state.tryonDesign==="custom"?"":"secondary"} wide" style="margin-top:9px" id="use-custom-design">使用当前九宫格作品</button><button class="button secondary wide" style="margin-top:7px" data-route="create">编辑九宫格 →</button>
    <h2 class="section-title" style="margin-top:17px">3. 佩戴部位</h2><div class="chips">${[["head","头饰"],["hair","发带"],["wrist","手环"],["clothing","服饰配饰"]].map(([id,label])=>`<button class="chip ${state.placement===id?"active":""}" data-placement="${id}">${label}</button>`).join("")}</div>
    <h2 class="section-title" style="margin-top:17px">4. 尺寸与位置</h2>${[["scale","宽度",55,150,"%"],["x","水平位置",0,100,""],["y","垂直位置",0,100,""]].map(([id,label,min,max,unit])=>`<div class="field"><label for="${id}">${label}<span class="range-value">${state[id]}${unit}</span></label><input id="${id}" type="range" min="${min}" max="${max}" value="${state[id]}"></div>`).join("")}
    <button class="button wide" id="generate-tryon">生成试戴示意图</button><p class="small muted">当前为前端位置叠加，不是生成式 AI；发丝遮挡、光影融合需后续接入模型。</p></section>
    <section class="panel tryon-column"><h2 class="section-title">实时预览 <span class="badge">${state.tryonDesign==="custom"?"我的九宫格":"系统搭配"}</span></h2><div class="portrait-stage ${state.tryonShow?"":"bare"}" id="portrait-stage"><img class="uploaded-portrait" src="${state.photoUrl||"./assets/system-model.png"}" alt="${state.photoUrl?"本次上传的照片":"系统示例模特"}"><div class="wearable" style="${wearableStyle()}">${wearableCells()}</div></div><p class="small muted">拖动下方滑块调整位置；上传照中请尽量保持正面或侧面清晰。</p></section>
    <section class="panel tryon-column compare-panel"><h2 class="section-title">试戴前后对比</h2><div class="compare-row"><div><div class="tryon-thumb"><img src="${state.photoUrl||"./assets/system-model.png"}" alt="试戴前照片" style="width:100%;height:100%;object-fit:cover"></div><small>试戴前</small></div><div><div class="tryon-thumb" style="position:relative"><img src="${state.photoUrl||"./assets/system-model.png"}" alt="试戴后示意" style="width:100%;height:100%;object-fit:cover"><div class="wearable" style="${wearableStyle()}">${wearableCells()}</div></div><small>试戴后示意</small></div></div><button class="button secondary wide" id="toggle-compare" style="margin:12px 0">${state.tryonShow?"隐藏佩戴效果":"显示佩戴效果"}</button><h2 class="section-title">场景成片</h2><div class="scene-card">${crop("sceneTryon","rounded")}<p class="small muted">场景图为原型视觉参考；生成式场景成片尚未接入。</p></div><button class="button wide" id="download-tryon">下载试戴示意图</button></section></div>`;}
  function weaveControls(){const s=state.weaveStep;if(s===0)return `<div class="weave-action-list"><span>木制支撑</span><span>“用叉” · 挑线</span><span>“打玛” · 压线</span></div><button class="button secondary" data-weave-action="tools">${state.weaveTools?"✓ 已辨认工具":"辨认并摆放工具"}</button><p class="small muted">工具名称沿用文献术语；主场景为概念图，不是工艺照片复刻。</p>`;
    if(s===1)return `<div class="weave-swatches">${palettes.map((p,i)=>`<button class="${state.weaveColor===i?"active":""}" data-weave-color="${i}" style="background:${p.hex}" aria-label="选择${p.name}" aria-pressed="${state.weaveColor===i}"></button>`).join("")}</div><div class="field"><label for="weave-count">示意线组数 <strong>${state.weaveCount}</strong></label><input id="weave-count" type="range" min="8" max="24" step="2" value="${state.weaveCount}"></div><button class="button secondary" data-weave-action="layout">${state.weaveLayout?"✓ 已按图案拉线":"按图案完成拉线"}</button><p class="small muted">线组越多通常可形成更宽的锦带；这里的数字不代表真实用线根数或实测宽度。</p>`;
    if(s===2)return `<p>依次安置三组提经杆，使上下两层经线可分组提起。</p><button class="button secondary" data-weave-action="heddle" ${state.weaveHeddles>=3?"disabled":""}>${state.weaveHeddles>=3?"✓ 三组已安置":`安置第 ${state.weaveHeddles+1} 组提经杆`}</button><span class="badge" role="status">${state.weaveHeddles}/3 组</span>`;
    if(s===3)return `<button class="button secondary" data-weave-action="fixed">${state.weaveFixed?"✓ 固定杆已安置":"绕线并安置固定杆"}</button><p class="small">文献中的“丝”是缠绕固定线组的竹杆；此处为简化示意。</p>`;
    if(s===4)return `<p>先点击画面中的经线选取图案线组，或使用下方按钮；再完成一次挑线引纬和压紧。</p><button class="button secondary" id="weave-pick-demo">选取示意线组</button><span class="badge" role="status">已选 ${state.weaveSelected.length} 根</span><div class="weave-action-list"><button class="button secondary" data-weave-action="pass" ${state.weavePass||!state.weaveSelected.length?"disabled":""}>${state.weavePass?"✓ 已挑线引纬":"用叉挑线并引纬"}</button><button class="button secondary" data-weave-action="beat" ${state.weavePass?"":"disabled"}>用打玛压紧</button><button class="button secondary" data-weave-action="repeat" ${state.weaveRounds<1?"disabled":""}>再织一轮（简化）</button></div><span class="badge" role="status">已织 ${state.weaveRounds} 轮</span>`;
    return `<p>前五段对应文献描述的工序。本步只展示数字结果，真实下机、收边和整圈推进的细节仍待传承人核对。</p>`;}
  function renderWeave(){const s=state.weaveStep;const sceneLabels=[["工具摆放区","木制支撑与挑压工具","准备拉线"],["线组沿两端往返","按图案排列彩线","双层经线形成"],["提经杆“尼” × 3","分组提起经线","上下两层经线"],["固定杆“丝”","绕线固定未织线组","保持线束有序"],["脚端木方支撑","腰部近端固定","用叉挑线 · 打玛压紧"],["数字成带展示","腰脚固定的织造姿态","真实收边未复原"]][s];return `${pageHead("经纬沉浸工坊","沿文献记载的工序，第一视角体验舟曲锦带织造","织")}
    <div class="weave-layout"><section class="weave-scene panel" aria-label="第一视角织带概念场景">${sceneImage("weave-photo")}<span class="weave-concept-badge">第一视角概念图 · 非工艺复原</span><span class="overlay-label foot">${sceneLabels[0]}</span><span class="overlay-label waist">${sceneLabels[1]}</span><span class="overlay-label warp">${sceneLabels[2]}</span>${s===4?`<div class="interactive-threads" aria-label="可选择的示意经线">${Array.from({length:state.weaveCount},(_,i)=>`<button class="thread ${state.weaveSelected.includes(i)?"selected":""}" data-thread="${i}" aria-label="第 ${i+1} 根经线" aria-pressed="${state.weaveSelected.includes(i)}"></button>`).join("")}</div>`:""}<div class="weave-progress" role="status" style="--progress:${Math.min(state.weaveRounds,4)*25}%"><span>已织 ${state.weaveRounds} 轮（数字示意）</span><i><b></b></i></div><div class="scene-controls"><button class="scene-cta" id="scene-continue">${s===5?"完成体验":"进入下一步"} →</button><button id="scene-help">文献与工艺说明</button><button id="scene-view">双层经线示意</button></div></section>
    <section class="weave-guide panel"><h2 class="section-title">制作步骤 <span class="muted small">${s+1}/6</span></h2><p class="small muted weave-source-note">前五段依据杨路色《白龙江流域织锦带工艺的传承与保护研究》“制作锦带的工艺流程”（《中国服饰》86–87 页）；第六段为平台回顾界面。</p><div class="weave-steps">${steps.map((step,i)=>`<button class="weave-step ${s===i?"active":""}" data-weave-step="${i}" ${s===i?'aria-current="step"':""}><b>${String(i+1).padStart(2,"0")}</b><span><strong>${step.title}</strong><small>${step.desc}</small></span></button>`).join("")}</div><div class="weave-controls"><h3>${steps[s].title}</h3><p>${steps[s].desc}</p>${weaveControls()}<div class="weave-actions"><button class="button" id="weave-next">${steps[s].action}</button><button class="button secondary" id="weave-reset">从头开始</button></div></div></section></div>
    <div class="weave-footer"><section class="panel"><h3>拉线方案 · 数字示意</h3><p class="small muted">${state.weaveCount} 组示意线 · ${palettes[state.weaveColor].name} · 不对应实测宽度</p><div class="swatches">${palettes.slice(0,5).map(p=>`<span class="swatch" style="background:${p.hex}"></span>`).join("")}</div></section><section class="panel"><h3>提经与固定</h3><div class="mini-diagram" role="img" aria-label="上下两层彩色经线的简化示意"></div><p class="small muted">三组提经杆“尼”用于分层；“丝”用于固定线束。</p></section><section class="panel"><h3>“搭” · 织造循环</h3><div class="weave-action-list"><span>① 用叉挑线</span><span>② 引纬</span><span>③ 打玛压紧</span><span>④ 反复织造</span></div><p class="small muted">依据文献梳理的交互示意；概念画面与真实细节仍需当地制作者校核。</p></section></div>`;}
  function renderExhibit(){const c=chapters[state.chapter];return `${pageHead("数字展厅","循着六个章节，走近舟曲锦带的文化与织造故事")}
    <div class="exhibit-layout"><section class="hall panel" aria-label="当前展厅章节">${sceneImage(c.image)}<button class="hall-nav prev" data-chapter="${(state.chapter+5)%6}" aria-label="上一展厅">‹</button><button class="hall-nav next" data-chapter="${(state.chapter+1)%6}" aria-label="下一展厅">›</button><button class="hotspot" id="hall-hotspot" aria-label="查看当前展品介绍">i</button><div class="hall-caption"><strong>${c.name}</strong><div class="small">${c.desc}</div></div></section></div>
    <div class="content-divider"><h2>展厅章节</h2><span class="muted small">${state.chapter+1} / 6</span></div><div class="chapters">${chapters.map((x,i)=>`<button class="chapter ${state.chapter===i?"active":""}" data-chapter="${i}"><div class="chapter-image">${sceneImage(x.image)}</div><span>${String(i+1).padStart(2,"0")} ${x.name}</span></button>`).join("")}</div>`;}
  async function saveDesign(){const work={title:state.theme.trim()||"未命名锦带",cells:[...state.cells],palette:state.palette};try{localStorage.setItem("zhouqu_jindai_design_v3",JSON.stringify(work));}catch{}if(!backendOnline){toast("后端未连接，作品已尝试保存在当前浏览器。");return;}try{const saved=await api(activeDesignId?`/designs/${activeDesignId}`:"/designs",{method:activeDesignId?"PUT":"POST",body:JSON.stringify(work)});activeDesignId=saved.id;savedDesigns=await api("/designs");render();toast("作品已保存到本机服务，可从“我的作品”读取。");}catch(e){toast(`保存失败：${e.message}`);}}
  function showDesigns(){if(!backendOnline){toast("后端未连接，暂无法读取作品列表。");return;}modal(`<h2>我的作品</h2><p class="small muted">保存在本机服务、当前浏览器的访客空间中；清除浏览器 Cookie 后可能无法再访问。</p>${savedDesigns.length?`<div class="saved-design-list">${savedDesigns.map(d=>`<div class="saved-design-row"><span><strong>${escapeHtml(d.title)}</strong><small>${escapeHtml(d.updatedAt)}</small></span><button class="button secondary" data-load-design="${d.id}">载入</button><button class="button secondary" data-delete-design="${d.id}" aria-label="删除${escapeHtml(d.title)}">删除</button></div>`).join("")}</div>`:"<p>还没有保存的作品。</p>"}`);}
  function showArchiveDetail(i){const item=archiveItems()[i];if(!item)return;modal(`<h2>${escapeHtml(item.title)}</h2>${sceneImage(item.image)}<p>${escapeHtml(item.summary)}</p><dl class="archive-meta"><dt>来源</dt><dd>${escapeHtml(item.source||"待补充")}</dd><dt>授权</dt><dd>${item.rightsStatus==="cleared"?"已标记授权":"待确认"}</dd><dt>核验</dt><dd>${item.verificationStatus==="verified"?"已标记核验":"待核验"}</dd></dl><div class="rule-note">${item.isDemo===false?"请结合来源与核验状态使用本资料。":"这是平台交互演示，不是真实馆藏档案。年代、尺寸、来源、版权与文化释义需由团队补充并核验。"}</div><button class="button" data-route="culture" style="margin-top:16px">进入文化解码 →</button>`);}
  function downloadTryon(){const stage=$("#portrait-stage"),source=stage?.querySelector("img"),canvas=document.createElement("canvas");if(!source?.complete||!source.naturalWidth){toast("照片仍在加载，请稍后重试。");return;}canvas.width=900;canvas.height=1100;const ctx=canvas.getContext("2d");const r=Math.max(900/source.naturalWidth,1100/source.naturalHeight),w=source.naturalWidth*r,h=source.naturalHeight*r;try{ctx.drawImage(source,(900-w)/2,(1100-h)/2,w,h);const wearable=$(".wearable",stage),box=stage.getBoundingClientRect(),band=wearable.getBoundingClientRect();const bx=(band.left-box.left)/box.width*900,by=(band.top-box.top)/box.height*1100,bw=band.width/box.width*900,bh=Math.max(14,band.height/box.height*1100);ctx.fillStyle="#eed5a7";ctx.fillRect(bx-3,by-3,bw+6,bh+6);for(let i=0;i<bw;i+=21){ctx.fillStyle=i%42===0?palettes[state.palette].hex:"#173f58";ctx.fillRect(bx+i,by,Math.min(21,bw-i),bh);}ctx.fillStyle="#ffffffdd";ctx.fillRect(0,1040,900,60);ctx.fillStyle="#1b3954";ctx.font="22px sans-serif";ctx.fillText("舟曲锦带 · 前端试戴示意（非 AI 生成）",20,1077);canvas.toBlob(blob=>{if(!blob){toast("导出失败，请稍后重试。");return;}const url=URL.createObjectURL(blob),a=document.createElement("a");a.href=url;a.download="舟曲锦带-试戴示意.png";a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);toast("已导出前端试戴示意图。")},"image/png");}catch{toast("当前浏览器无法导出此图，请通过本地服务器运行。");}}
  function changeWeaveStep(next){state.weaveStep=Math.max(0,Math.min(5,next));render();}
  function advanceWeave(){const s=state.weaveStep;if(s===0&&!state.weaveTools){toast("请先辨认并摆放工具。");return;}if(s===1&&!state.weaveLayout){toast("请先按图案完成拉线示意。");return;}if(s===2&&state.weaveHeddles<3){toast("请依次安置三组提经杆。");return;}if(s===3&&!state.weaveFixed){toast("请先安置固定杆。");return;}if(s===4&&state.weaveRounds<2){toast("请先挑线、引纬、压紧，并至少再织一轮。");return;}if(s===5){modal(`<h2>数字锦带已完成</h2><p>你体验了文献所述的摆放工具、拉线、安置提经杆、安置固定杆与“搭”（织造）五段工序。</p><div class="rule-note">这是数字教学示意。文献没有完整交代下机、收边及整圈推进动作；具体工具摆位、线序和手法仍需当地制作者校核。</div><button class="button" data-route="create" style="margin-top:16px">去设计我的锦带</button>`);return;}changeWeaveStep(s+1);}
  function handleClick(e){const t=e.target,nav=t.closest("[data-route]");if(nav){if($("#modal").open)$("#modal").close();route(nav.dataset.route);return;}
    const filter=t.closest("[data-filter]");if(filter){state.archiveFilter=filter.dataset.filter;render();return;}
    const feature=t.closest("[data-feature]");if(feature){state.archiveItem=Number(feature.dataset.feature);render();window.scrollTo({top:0,behavior:"smooth"});return;}
    const detail=t.closest("[data-detail]");if(detail){showArchiveDetail(Number(detail.dataset.detail));return;}
    const tab=t.closest("[data-culture-tab]");if(tab){state.cultureTab=tab.dataset.cultureTab;render();return;}
    const node=t.closest("[data-culture-node]");if(node){modal(`<h2>${escapeHtml(node.dataset.cultureNode)} · 文化关联</h2><p>这一要素与纹样的关系将在正式资料采集后填写。原型仅展示知识网络的交互方式。</p><div class="rule-note">待采集：原始图像、出处、地方称谓、使用场景及审核记录。</div>`);return;}
    if(t.closest("#shuffle-suggestions")){state.suggestion=(state.suggestion+1)%6;render();return;}
    const sug=t.closest("[data-suggestion]");if(sug){state.suggestion=Number(sug.dataset.suggestion);render();toast("已切换纹样视觉示例。");return;}
    if(t.closest("#speak-button")){if(!("speechSynthesis" in window)){toast("当前浏览器不支持语音朗读。");return;}if(window.speechSynthesis.speaking){window.speechSynthesis.cancel();t.textContent="▶";}else{speech=new SpeechSynthesisUtterance(cultureTabs[state.cultureTab]);speech.lang="zh-CN";speech.onend=()=>{const b=$("#speak-button");if(b)b.textContent="▶";};window.speechSynthesis.speak(speech);t.textContent="Ⅱ";}return;}
    const preset=t.closest("[data-preset]");if(preset){state.preset=Number(preset.dataset.preset);state.cells=[...presets[state.preset].ids];render();return;}
    const mode=t.closest("[data-mode]");if(mode){state.preset=mode.dataset.mode==="preset"?0:-1;if(state.preset===0)state.cells=[...presets[0].ids];render();return;}
    const motif=t.closest("[data-motif]");if(motif){state.selectedMotif=Number(motif.dataset.motif);if(state.route==="tryon")state.tryonDesign="system";renderKeepingMotifScroll();return;}
    const kind=t.closest("[data-motif-kind]");if(kind){state.motifFilter=kind.dataset.motifKind;render();return;}
    const cell=t.closest("[data-cell]");if(cell){state.cells[Number(cell.dataset.cell)]=state.selectedMotif;state.preset=-1;renderKeepingMotifScroll();return;}
    const palette=t.closest("[data-palette]");if(palette){state.palette=Number(palette.dataset.palette);render();return;}
    if(t.closest("#reset-grid")){state.cells=[...presets[0].ids];state.preset=0;render();return;}
    if(t.closest("#random-grid")){state.cells=Array.from({length:9},()=>Math.floor(Math.random()*motifs.length));state.preset=-1;render();return;}
    if(t.closest("#save-design")){saveDesign();return;}
    if(t.closest("#new-design")){activeDesignId=null;toast("已准备新作品；编辑后点击“保存作品”即可另存。");return;}
    if(t.closest("#my-designs")){showDesigns();return;}
    const load=t.closest("[data-load-design]");if(load){const work=savedDesigns.find(d=>d.id===load.dataset.loadDesign);if(work){$("#modal").close();loadDesign(work);}return;}
    const remove=t.closest("[data-delete-design]");if(remove){const work=savedDesigns.find(d=>d.id===remove.dataset.deleteDesign);if(!work||!confirm(`确定删除《${work.title}》吗？此操作无法撤销。`))return;api(`/designs/${work.id}`,{method:"DELETE"}).then(()=>{savedDesigns=savedDesigns.filter(d=>d.id!==work.id);if(activeDesignId===work.id)activeDesignId=null;showDesigns();toast("作品已删除。")}).catch(e=>toast(`删除失败：${e.message}`));return;}
    if(t.closest("#use-custom-design")){state.tryonDesign="custom";render();return;}
    const placement=t.closest("[data-placement]");if(placement){state.placement=placement.dataset.placement;render();return;}
    if(t.closest("#system-photo")){if(state.photoUrl)URL.revokeObjectURL(state.photoUrl);state.photoUrl=null;render();return;}
    if(t.closest("#toggle-compare")){state.tryonShow=!state.tryonShow;render();return;}
    if(t.closest("#generate-tryon")){state.tryonShow=true;render();toast("已生成前端试戴示意。AI 精修尚未接入。");return;}
    if(t.closest("#download-tryon")){downloadTryon();return;}
    const step=t.closest("[data-weave-step]");if(step){changeWeaveStep(Number(step.dataset.weaveStep));return;}
    const color=t.closest("[data-weave-color]");if(color){state.weaveColor=Number(color.dataset.weaveColor);render();return;}
    const thread=t.closest("[data-thread]");if(thread){const i=Number(thread.dataset.thread);state.weaveSelected=state.weaveSelected.includes(i)?state.weaveSelected.filter(x=>x!==i):[...state.weaveSelected,i];render();return;}
    if(t.closest("#weave-pick-demo")){const middle=Math.floor(state.weaveCount/2);state.weaveSelected=[middle-1,middle,middle+1].filter(i=>i>=0&&i<state.weaveCount);render();toast("已选取示意线组。");return;}
    const action=t.closest("[data-weave-action]");if(action){const kind=action.dataset.weaveAction;if(kind==="tools")state.weaveTools=true;if(kind==="layout")state.weaveLayout=true;if(kind==="heddle")state.weaveHeddles=Math.min(3,state.weaveHeddles+1);if(kind==="fixed")state.weaveFixed=true;if(kind==="pass"&&state.weaveSelected.length)state.weavePass=true;if(kind==="beat"&&state.weavePass){state.weavePass=false;state.weaveBeat=true;state.weaveRounds++;toast("已完成一次挑线、引纬与打玛压紧示意。");}if(kind==="repeat"&&state.weaveRounds>=1){state.weaveRounds++;toast("又完成一轮简化织造。");}render();return;}
    if(t.closest("#weave-next")||t.closest("#scene-continue")){advanceWeave();return;}
    if(t.closest("#weave-reset")){state.weaveStep=0;state.weaveSelected=[];state.weaveRounds=0;state.weavePass=false;state.weaveBeat=false;state.weaveTools=false;state.weaveLayout=false;state.weaveHeddles=0;state.weaveFixed=false;render();return;}
    if(t.closest("#scene-help")){modal(`<h2>文献依据与演示范围</h2><p>杨路色《白龙江流域织锦带工艺的传承与保护研究》在“制作锦带的工艺流程”中依次记载：摆放工具、拉线、安置提经杆“尼”、安置固定杆“丝”、以及“搭”（织造）。</p><p>文献描述织造时坐姿伸脚，脚端以木方支撑、近端在腰部固定，用“用叉”按图案挑线，再用“打玛”压紧。当前画面为第一视角概念示意，不是原文图片或实际工艺录像。</p><div class="rule-note">来源：《中国服饰》86–87 页。各村寨具体器具和操作差异、下机收边方式需传承人进一步核对。</div>`);return;}
    if(t.closest("#scene-view")){modal(`<h2>双层经线 · 提经示意</h2><div class="mini-diagram" style="height:160px;margin:14px 0"></div><p>文献记载布线后形成上下两层，依次安置三组提经杆“尼”以分组提起线束；本图只表示层次关系，不复原真实线序。</p>`);return;}
    const chapter=t.closest("[data-chapter]");if(chapter){state.chapter=Number(chapter.dataset.chapter);render();return;}
    if(t.closest("#hall-hotspot")){modal(`<h2>${chapters[state.chapter].name}</h2><p>${chapters[state.chapter].desc}</p><p class="rule-note">展品信息、馆藏来源与影像授权均待正式采集。</p><button class="button" data-route="archive" style="margin-top:15px">查看数字档案</button>`);return;}
    if(t.closest("#archive-search-button")){state.archiveQuery=$("#archive-search").value;render();return;}
  }
  function handleInput(e){const t=e.target;if(t.id==="global-search"){return;}if(t.id==="archive-search"){state.archiveQuery=t.value;const caret=t.selectionStart;render();const input=$("#archive-search");input.focus();input.setSelectionRange(caret,caret);return;}if(t.id==="theme"){state.theme=t.value;return;}if(["scale","x","y"].includes(t.id)){state[t.id]=Number(t.value);const wearable=$("#portrait-stage .wearable");if(wearable)wearable.style.cssText=wearableStyle();$$(".compare-row .wearable").forEach(el=>el.style.cssText=wearableStyle());const value=$("#"+t.id).closest(".field").querySelector(".range-value");value.textContent=t.value+(t.id==="scale"?"%":"");return;}if(t.id==="weave-count"){state.weaveCount=Number(t.value);const label=t.closest(".field")?.querySelector("strong");if(label)label.textContent=t.value;return;}}
  function handleChange(e){const t=e.target;if(t.id==="weave-count"){render();return;}if(t.id!=="photo-upload")return;const file=t.files?.[0];if(!file)return;if(!/^image\/(png|jpeg|webp)$/.test(file.type)||file.size>10*1024*1024){toast("请上传 10MB 以下的 PNG、JPG 或 WebP 图片。");return;}const url=URL.createObjectURL(file);if(state.photoUrl)URL.revokeObjectURL(state.photoUrl);state.photoUrl=url;render();toast("照片已在本机载入。");}
  let dragCell=null;document.addEventListener("dragstart",e=>{const c=e.target.closest("[data-cell]");if(c)dragCell=Number(c.dataset.cell);});document.addEventListener("dragover",e=>{if(e.target.closest("[data-cell]"))e.preventDefault();});document.addEventListener("drop",e=>{const c=e.target.closest("[data-cell]");if(c&&dragCell!==null){e.preventDefault();const i=Number(c.dataset.cell);[state.cells[i],state.cells[dragCell]]=[state.cells[dragCell],state.cells[i]];state.preset=-1;dragCell=null;render();}});
  document.addEventListener("click",handleClick);document.addEventListener("input",handleInput);document.addEventListener("change",handleChange);
  document.addEventListener("click",()=>{if(state.route==="weave")queueProgress();});
  document.addEventListener("change",e=>{if(e.target.id==="weave-count")queueProgress();});
  $("#modal-close").addEventListener("click",()=>$("#modal").close());$("#modal").addEventListener("click",e=>{if(e.target===$("#modal"))$("#modal").close();});
  $("#menu-button").addEventListener("click",()=>{const open=$("#sidebar").classList.toggle("open");$("#menu-button").setAttribute("aria-expanded",String(open));});
  $("#global-search").addEventListener("keydown",e=>{if(e.key==="Enter"){state.archiveQuery=e.target.value;route("archive");}});
  window.addEventListener("hashchange",()=>{const id=location.hash.slice(1);if(routes.some(r=>r[0]===id)){state.route=id;render();}});
  window.addEventListener("beforeunload",()=>{if(state.photoUrl)URL.revokeObjectURL(state.photoUrl);});
  try{const saved=JSON.parse(localStorage.getItem("zhouqu_jindai_design_v3")||"null");if(saved&&Array.isArray(saved.cells)&&saved.cells.length===9){state.theme=String(saved.title||defaults.theme).slice(0,20);state.cells=saved.cells.map(n=>Number.isInteger(n)&&n>=0&&n<motifs.length?n:null);state.palette=Math.min(7,Math.max(0,Number(saved.palette)||0));state.preset=-1;}}catch{}
  state.route=routes.some(r=>r[0]===location.hash.slice(1))?location.hash.slice(1):"archive";render();connectBackend();
})();
