const { chromium } = require('playwright');

(async () => {
  const browser = await chromium.launch({ headless: true, executablePath: process.env.BROWSER_EXECUTABLE });
  const page = await browser.newPage({ viewport: { width: 1440, height: 900 } });
  const errors = [];
  page.on('pageerror', error => errors.push(error.message));
  await page.goto(process.env.BASE_URL || 'http://127.0.0.1:8766/', { waitUntil: 'networkidle' });
  for (const route of ['archive', 'culture', 'create', 'tryon', 'weave', 'exhibit']) {
    await page.locator(`[data-route="${route}"]`).first().click();
    await page.waitForTimeout(100);
    await page.screenshot({ path: `./smoke-${route}.png`, fullPage: true });
    if (!(await page.locator('main').innerText()).trim()) throw new Error(`Empty route: ${route}`);
  }
  await page.locator('[data-route="create"]').first().click();
  if (await page.locator('#motif-picker [data-motif]').count() !== 35) throw new Error('Missing repository motif photos');
  await page.locator('[data-motif-kind="红白"]').click();
  if (await page.locator('#motif-picker [data-motif]').count() !== 8) throw new Error('Motif color filter is incorrect');
  await page.locator('[data-motif-kind="混合"]').click();
  await page.locator('#motif-picker [data-motif="34"]').click();
  await page.locator('[data-cell="0"]').first().click();
  if (!(await page.locator('[data-cell="0"] img').getAttribute('src')).endsWith('35.jpg')) throw new Error('Nine-grid did not use selected repository photo');
  if (await page.locator('.ribbon-stack .motif-tile').count() !== 45) throw new Error('Long preview must repeat the nine-grid five times');
  const previewOrder = await page.locator('.ribbon-stack .motif-tile').evaluateAll(tiles => tiles.map(tile => Number(tile.dataset.sourceCell)));
  if (previewOrder.join(',') !== Array.from({ length: 45 }, (_, i) => i % 9).join(',')) throw new Error('Preview is not five continuous nine-grid units');
  const editorTile = await page.locator('[data-cell="0"]').boundingBox();
  const previewTile = await page.locator('.ribbon-stack .motif-tile').first().boundingBox();
  if (Math.abs(editorTile.width - editorTile.height) > 1 || Math.abs(previewTile.width - previewTile.height) > 1) throw new Error('Editor or preview tile is not square');
  const longRibbon = await page.locator('.ribbon-stack').boundingBox();
  if (longRibbon.height / longRibbon.width < 4.5) throw new Error('Preview is not long and narrow');
  await page.setViewportSize({ width: 1910, height: 917 });
  const wideEditorTile = await page.locator('[data-cell="0"]').boundingBox();
  const widePreviewTile = await page.locator('.ribbon-stack .motif-tile').first().boundingBox();
  if (Math.abs(wideEditorTile.width - wideEditorTile.height) > 1 || Math.abs(widePreviewTile.width - widePreviewTile.height) > 1) throw new Error('Wide-screen editor or preview tile is not square');
  await page.screenshot({ path: './smoke-create-wide.png', fullPage: true });
  await page.setViewportSize({ width: 1440, height: 900 });
  await page.locator('#save-design').click();
  await page.waitForFunction(() => document.querySelector('#toast')?.textContent?.includes('本机服务'));
  await page.locator('#my-designs').click();
  if (await page.locator('[data-load-design]').count() < 1) throw new Error('Saved design list is empty');
  await page.locator('#modal-close').click();
  await page.reload();
  if (!(await page.locator('[data-cell="0"] img').getAttribute('src')).endsWith('35.jpg')) throw new Error('Create state not restored');
  await page.locator('[data-route="weave"]').first().click();
  await page.locator('#weave-next').click();
  if (!(await page.locator('.weave-step.active').innerText()).includes('摆放工具')) throw new Error('Weaving advanced before tool setup');
  await page.locator('[data-weave-action="tools"]').click();
  await page.locator('#weave-next').click();
  if (!(await page.locator('.weave-step.active').innerText()).includes('拉线')) throw new Error('Weaving did not reach warp layout');
  await page.locator('[data-weave-action="layout"]').click();
  await page.locator('#weave-next').click();
  for (let i = 0; i < 3; i++) await page.locator('[data-weave-action="heddle"]').click();
  await page.locator('#weave-next').click();
  await page.locator('[data-weave-action="fixed"]').click();
  await page.locator('#weave-next').click();
  if (!(await page.locator('.weave-step.active').innerText()).includes('搭')) throw new Error('Weaving did not reach the documented weaving step');
  await page.locator('[data-thread="1"]').click();
  await page.locator('[data-weave-action="pass"]').click();
  await page.locator('[data-weave-action="beat"]').click();
  await page.locator('[data-weave-action="repeat"]').click();
  if (!(await page.locator('.weave-progress').innerText()).includes('2 轮')) throw new Error('Weaving progress did not update');
  await page.locator('#weave-next').click();
  if (!(await page.locator('.weave-step.active').innerText()).includes('成带回顾')) throw new Error('Weaving did not reach digital review');
  await page.locator('[data-route="exhibit"]').first().click();
  if (!(await page.locator('.page-head h1').innerText()).includes('数字展厅')) throw new Error('Gallery title is missing');
  if (await page.locator('.ar-panel, #ar-upload, #ar-info').count()) throw new Error('AR guidance is still visible');
  const hallBox = await page.locator('.hall').boundingBox();
  const exhibitBox = await page.locator('.exhibit-layout').boundingBox();
  if (Math.abs(hallBox.width - exhibitBox.width) > 2) throw new Error('Gallery scene does not use the full width');
  await page.locator('[data-chapter="2"]').first().click();
  await page.locator('#hall-hotspot').click();
  if (!(await page.locator('#modal').evaluate(el => el.open))) throw new Error('Gallery exhibit detail did not open');
  await page.locator('#modal-close').click();
  await page.locator('[data-route="tryon"]').first().click();
  await page.locator('#photo-upload').setInputFiles('./assets/system-model.png');
  await page.waitForFunction(() => document.querySelector('#portrait-stage .uploaded-portrait')?.getAttribute('src')?.startsWith('blob:'));
  if (!(await page.locator('#portrait-stage .uploaded-portrait').getAttribute('src')).startsWith('blob:')) throw new Error('Photo upload not loaded');
  await page.locator('#system-photo').click();
  await page.setViewportSize({ width: 390, height: 844 });
  await page.locator('#menu-button').click();
  await page.locator('[data-route="create"]').first().click();
  const mobileTile = await page.locator('[data-cell="0"]').boundingBox();
  if (Math.abs(mobileTile.width - mobileTile.height) > 1) throw new Error('Mobile editor tile is not square');
  if (await page.evaluate(() => document.documentElement.scrollWidth > window.innerWidth + 2)) throw new Error('Mobile creator horizontal overflow');
  await page.locator('#menu-button').click();
  await page.locator('[data-route="weave"]').first().click();
  await page.locator('#weave-reset').click();
  await page.waitForTimeout(3500);
  await page.screenshot({ path: './smoke-weave-mobile.png', fullPage: true });
  if (await page.evaluate(() => document.documentElement.scrollWidth > window.innerWidth + 2)) throw new Error('Mobile weaving horizontal overflow');
  await page.locator('#menu-button').click();
  await page.locator('[data-route="culture"]').first().click();
  await page.screenshot({ path: './smoke-mobile.png', fullPage: true });
  if (await page.evaluate(() => document.documentElement.scrollWidth > window.innerWidth + 2)) throw new Error('Mobile horizontal overflow');
  await page.locator('#menu-button').click();
  await page.locator('[data-route="exhibit"]').first().click();
  await page.waitForTimeout(350);
  await page.screenshot({ path: './smoke-exhibit-mobile.png', fullPage: true });
  if (await page.evaluate(() => document.documentElement.scrollWidth > window.innerWidth + 2)) throw new Error('Mobile gallery horizontal overflow');
  if (await page.locator('.ar-panel, #ar-upload').count()) throw new Error('Mobile AR guidance is still visible');
  if (errors.length) throw new Error(errors.join('\n'));
  console.log('Smoke test passed: 6 routes, creator save, weave actions, exhibit switch, photo upload, mobile.');
  await browser.close();
})().catch(error => { console.error(error); process.exit(1); });
